name: favicon

on:
  push:
    branches:
      - "favicon"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ^1.15

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: build
        run: |
          sudo apt install libvips-dev -y
          GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -trimpath -ldflags "-s -w" -o favicon .

      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: favicon