name: sync feeds

on: 
  push:
    branches:
      - "feeds"

jobs:
  check:
    timeout-minutes: 30
    name: sync-feeds
    runs-on: ubuntu-latest
    steps:
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - id: set_commit_message
        run: |
          echo ::set-output name=COMMIT_MSG::$(git rev-parse --short HEAD)

      - id: debug
        run: |
          echo "${{ steps.set_commit_message.outputs.COMMIT_MSG }}"

      - name: sync to gitee
        run: |
          rm -rf .git
          git init
          git remote add origin "https://gitee.com/${{ secrets.YOUR_GITEE_NAME }}/${{ secrets.TARGET_NAME }}.git"  >/dev/null 2>&1
          git config user.name    "${{ secrets.YOUR_GITEE_NAME }}"
          git config user.email   "${{ secrets.YOUR_GITEE_EMAIL }}"
          git add .
          git gc
          COMMIT_MSG=$(date "+%Y-%m-%d %H:%M:%S")
          git commit -m "${{ steps.set_commit_message.outputs.COMMIT_MSG }}" >/dev/null 2>&1
          git checkout -b feeds  >/dev/null 2>&1
          git branch -d master  >/dev/null 2>&1
          git push -f --repo "https://${{ secrets.YOUR_GITEE_NAME }}:${{ secrets.YOUR_GITEE_PWD }}@gitee.com/${{ secrets.YOUR_GITEE_NAME }}/${{ secrets.TARGET_NAME }}.git"  >/dev/null 2>&1
